### ISSUE TITLE
Error parsing arguments when using custom localiazations

### ISSUE THREAD

**Issue by Ghostlyr** [TheE/MyWarp#101]
I'm using custom localization files (located on plugin folder) and get in some command messages  parsing arguments errors. But in server console no one error.

![46456456456](https://cloud.githubusercontent.com/assets/8511068/14783137/83e800e6-0b0f-11e6-914f-10c94e0e28fc.png)

Same with all "exception.*"  messages.

**Comment by TheE** [comment]
This is just a normal error.

When I updated the command parsing library, these new messages where introduced.

**Comment by Ghostlyr** [comment]
Roger that
Thank you for the quickly responds :+1:
