### ISSUE TITLE
Failed to get a connection to the database.

### ISSUE THREAD

**Issue by Zoom4ikDan4ik** [TheE/MyWarp#103]
Hello, read the instructions on the plugin connection to the MySQL but was not able to set up a normal connection. The plugin v3.0-beta-3. Are you trying to connect to the database the same machine.

> [12:58:47 INFO]: Database: jdbc:mysql://localhost:3306/testserver (MySQL 5.5)
> [12:58:47 INFO]: Repair of failed migration in metadata table `testserver`.`schema_version` not necessary. No failed migration detected.
> [12:58:47 INFO]: Metadata table `testserver`.`schema_version` successfully repaired (execution time 00:00.040s).
> [12:58:47 INFO]: Manual cleanup of the remaining effects the failed migration may still be required.
> [12:58:47 INFO]: Validated 3 migrations (execution time 00:00.022s)
> [12:58:49 ERROR]: [MyWarp] A critical failure has been encountered and MyWarp is unable to continue. MyWarp will be disabled.
> me.taylorkelly.mywarp.InitializationException: Failed to get a connection to the database.
>         at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:102) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:177) [%5BRUSF%5DMyWarp.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
>         at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
> Caused by: me.taylorkelly.mywarp.storage.StorageInitializationException: Failed to execute migration process.
>         at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:108) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:96) ~[%5BRUSF%5DMyWarp.jar:?]
>         ... 12 more
> Caused by: me.taylorkelly.mywarp.internal.flyway.core.api.FlywayException: Found non-empty schema `testserver` without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
>         at me.taylorkelly.mywarp.internal.flyway.core.Flyway$1.execute(Flyway.java:1035) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.internal.flyway.core.Flyway$1.execute(Flyway.java:1006) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1418) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.internal.flyway.core.Flyway.migrate(Flyway.java:1006) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:106) ~[%5BRUSF%5DMyWarp.jar:?]
>         at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:96) ~[%5BRUSF%5DMyWarp.jar:?]
>         ... 12 more

storage:
  schema: testserver
  user: testserver
  password: password
  url: jdbc:mysql://localhost:3306/testserver

**Comment by TheE** [comment]
The It appears as if the schema you specified does already contain tables. You need to use a dedicated schema for MyWarp and for MyWarp only.

Unfortunately it is technically impossible to update the database layout automatically if there are uncontrolled tables within the database schema.
