### ISSUE TITLE
Plugin folder does not exist

### ISSUE THREAD

**Issue by Neylion** [TheE/MyWarp#104]
Hello! I tried installing your latest dev build but I got the following errors:

http://pastebin.com/wbXg0BxG

Hope you'll be able to assist me by either telling me what I am doing wrong or fix the issue! :)
Thanks for updating!

**Comment by TheE** [comment]
It seems as if MyWarp's plugin folder was either not created by Bukkit or is not writable by MyWarp. Could you please look if the folder `/home/minecraft/Servers/Survival/plugins/MyWarp/` exists?

If it does not exist, could you create the folder and test again?

**Comment by Neylion** [comment]
Sorry for the late reply, but it seems to be working fine now!

Thanks :)

**Comment by Proplex** [comment]
For the record, getting the same issue on the latest commit. It seems MyWarp isn't creating the directory. Are you using a custom method for config saving/creation or Bukkit's getDataFolder()?

**Comment by TheE** [comment]
In fact I was using Bukkit's `getDataFolder()` but apparently the plugin folder is only created when Bukkit's `getConfig()` is used (which I do not).

Should be fixed now, although I need to have a look if my custom config logic is really needed.
