### ISSUE TITLE
Warps only show on DynMap until restart

### ISSUE THREAD

**Issue by khamseen** [TheE/MyWarp#105]
Running MyWarp v3.0-beta-3+jenkins-b98.git-623f42c
Spigot 1.9.2
DynMap v2.3-SNAPSHOT-1132

When I create a new public warp, it shows on the map ok but as soon as the server restarts all created warps vanish from DynMap and only warps created during the next session will show.

**Comment by TheE** [comment]
Could you try the lastest development build?

I think I changed how Dynmap warps are handled between the build you are using and the current versions which might have solved the issue.

**Comment by khamseen** [comment]
Just updated the latest build and it does appear to be working. Sorry, should have checked that first.
