### ISSUE TITLE
Warps completely resetting randomly

### ISSUE THREAD

**Issue by blazex224** [TheE/MyWarp#113]
I don't know what's causing this, but at random times after a server restart, warps completely reset and disappear. I'm using the version for 1.10
Thanks for any help!

**Comment by TheE** [comment]
Are there any error messages visible in the console? Could you test with the latest [development build ](https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/)?

Is there any pattern that involves the disappearing warps (e.g. they where created/updated shortly before the restart)? Can you check if these warps are written to the database?

**Comment by TheE** [comment]
Closing as I cannot reproduce the issue without additional input.
