### ISSUE TITLE
Player Locales are not parsed on 1.11

### ISSUE THREAD

**Issue by TickleMeCthulhu** [TheE/MyWarp#116]
Updated to 1.11- all warps are gone and any use of /warp gives my an internal error. Removed and reinstalled MyWarp and restarted the server. Also running Dynmap + Dynmap Essentials and no warps are showing.

Cleared the log and attempted to create a new warp and got this:

``````
Send
17.11 23:43:58 [Server] INFO ... 15 more
17.11 23:43:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:249) ~[?:?]
17.11 23:43:58 [Server] INFO at me.taylorkelly.mywarp.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:119) ~[?:?]
17.11 23:43:58 [Server] INFO at me.taylorkelly.mywarp.bukkit.util.parametric.ReflectiveLocaleResolver.resolve(ReflectiveLocaleResolver.java:99) ~[?:?]
17.11 23:43:58 [Server] INFO at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:118) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid locale format: en_us
17.11 23:43:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
17.11 23:43:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
17.11 23:43:58 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin MyWarp v3.0-SNAPSHOT+jenkins-b60.git-67b56dd
17.11 23:43:58 [Server] ERROR null
``````

**Comment by TheE** [comment]
I see that there is an issue with the parsing of player locales. Apparently Mojang changed their format in 1.11 - I will have to adapt to that.

However this should simply display a warning and not crash MyWarp (I just tested against 1.11). Apparently there are some lines missing above and beyond the snippet you just posted above.

Could you please post the **full** error-log?

**Comment by TickleMeCthulhu** [comment]
Okay, I will clear the log, start a new session and try some commands and then paste the contents of the log here.

**Comment by TickleMeCthulhu** [comment]
Okay, restarted the server and logged on, tried "/warp taffy," "mywarp," and "warp set wood."

18.11 16:18:59 [Server] INFO ... 15 more
18.11 16:18:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:249) ~[?:?]
18.11 16:18:59 [Server] INFO at me.taylorkelly.mywarp.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:119) ~[?:?]
18.11 16:18:59 [Server] INFO at me.taylorkelly.mywarp.bukkit.util.parametric.ReflectiveLocaleResolver.resolve(ReflectiveLocaleResolver.java:99) ~[?:?]
18.11 16:18:59 [Server] INFO at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:118) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid locale format: en_us
18.11 16:18:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
18.11 16:18:59 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin MyWarp v3.0-SNAPSHOT+jenkins-b60.git-67b56dd
18.11 16:18:59 [Server] ERROR null
18.11 16:18:49 [Server] INFO ... 15 more
18.11 16:18:49 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:249) ~[?:?]
18.11 16:18:49 [Server] INFO at me.taylorkelly.mywarp.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:119) ~[?:?]
18.11 16:18:49 [Server] INFO at me.taylorkelly.mywarp.bukkit.util.parametric.ReflectiveLocaleResolver.resolve(ReflectiveLocaleResolver.java:99) ~[?:?]
18.11 16:18:49 [Server] INFO at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:118) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid locale format: en_us
18.11 16:18:49 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
18.11 16:18:49 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:49 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mywarp' in plugin MyWarp v3.0-SNAPSHOT+jenkins-b60.git-67b56dd
18.11 16:18:49 [Server] ERROR null
18.11 16:18:34 [Server] INFO ... 15 more
18.11 16:18:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:249) ~[?:?]
18.11 16:18:34 [Server] INFO at me.taylorkelly.mywarp.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:119) ~[?:?]
18.11 16:18:34 [Server] INFO at me.taylorkelly.mywarp.bukkit.util.parametric.ReflectiveLocaleResolver.resolve(ReflectiveLocaleResolver.java:99) ~[?:?]
18.11 16:18:34 [Server] INFO at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:118) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid locale format: en_us
18.11 16:18:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
18.11 16:18:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:18:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin MyWarp v3.0-SNAPSHOT+jenkins-b60.git-67b56dd
18.11 16:18:34 [Server] ERROR null
18.11 16:18:24 [Multicraft] KurtKomoda ran command Message of the Day
18.11 16:18:24 [Connect] User KurtKomoda, IP 69.121.133.201
18.11 16:18:24 [Server] INFO UUID of player KurtKomoda is e60a0a9f-4711-4b87-9194-4f718c912188
18.11 16:18:18 [Server] INFO Full render of map 'surface' of 'world' in progress - 439600 tiles rendered (126.23 msec/tile, 72.21 msec per render)
18.11 16:18:08 [Server] INFO Full render of map 'surface' of 'world' in progress - 439500 tiles rendered (126.24 msec/tile, 73.37 msec per render)
18.11 16:17:58 [Server] INFO Full render of map 'surface' of 'world' in progress - 439400 tiles rendered (126.25 msec/tile, 73.67 msec per render)
18.11 16:17:43 [Server] INFO Full render of map 'surface' of 'world' in progress - 439300 tiles rendered (126.24 msec/tile, 69.25 msec per render)
18.11 16:17:31 [Server] INFO Full render of map 'surface' of 'world' in progress - 439200 tiles rendered (126.24 msec/tile, 68.19 msec per render)
18.11 16:17:19 [Server] INFO Full render of map 'surface' of 'world' in progress - 439100 tiles rendered (126.25 msec/tile, 70.45 msec per render)
18.11 16:17:05 [Server] INFO Full render of map 'surface' of 'world' in progress - 439000 tiles rendered (126.24 msec/tile, 66.66 msec per render)
18.11 16:16:53 [Server] INFO Full render of map 'surface' of 'world' in progress - 438900 tiles rendered (126.24 msec/tile, 64.58 msec per render)
18.11 16:16:41 [Server] INFO Full render of map 'surface' of 'world' in progress - 438800 tiles rendered (126.25 msec/tile, 61.14 msec per render)
18.11 16:16:30 [Server] INFO Full render of map 'surface' of 'world' in progress - 438700 tiles rendered (126.25 msec/tile, 59.04 msec per render)
18.11 16:16:16 [Server] INFO Full render of map 'surface' of 'world' in progress - 438600 tiles rendered (126.25 msec/tile, 49.59 msec per render)
18.11 16:16:05 [Server] INFO Full render of map 'surface' of 'world' in progress - 438500 tiles rendered (126.25 msec/tile, 48.48 msec per render)
18.11 16:15:56 [Server] INFO Full render of map 'surface' of 'world' in progress - 438400 tiles rendered (126.26 msec/tile, 49.44 msec per render)
18.11 16:15:49 [Server] INFO Full render of map 'surface' of 'world' in progress - 438300 tiles rendered (126.27 msec/tile, 71.00 msec per render)
18.11 16:15:44 [Server] INFO Loading default resource pack
18.11 16:15:44 [Multicraft] Skipped 76 lines due to rate limit (30/s)
18.11 16:15:39 [Server] Startup Done (6.303s)! For help, type "help" or "?"
18.11 16:15:39 [Server] Startup Done!
18.11 16:15:39 [Server] INFO ** When working with blocks or undoing, chests will be empty, signs
18.11 16:15:39 [Server] INFO **
18.11 16:15:39 [Server] INFO ** This WorldEdit version does not fully support your version of Bukkit.
18.11 16:15:39 [Server] INFO **********************************************
18.11 16:15:39 [Server] INFO WEPIF: Using the Bukkit Permissions API.
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.5.4
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@        @@        @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@        @@  @  @  @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@        @@        @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@        @@        @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
18.11 16:15:39 [Server] INFO @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
18.11 16:15:39 [Server] INFO Enabling WorldEdit v6.1.2;b3fbe8b
18.11 16:15:39 [Server] INFO [CreeperControl] Controlling Creepers 
18.11 16:15:39 [Server] INFO CreeperControl 0.5.1 (Build 85) is enabled!
18.11 16:15:39 [Server] INFO Enabling CreeperControl v0.5.1
18.11 16:15:38 [Server] INFO Loading warps...
18.11 16:15:38 [Server] INFO Schema "main" is up to date. No migration necessary.
18.11 16:15:38 [Server] INFO Current version of schema "main": 1.1
18.11 16:15:38 [Server] INFO Validated 2 migrations (execution time 00:00.026s)
18.11 16:15:38 [Server] INFO Database: jdbc:sqlite:///plugins/MyWarp/mywarp.db (SQLite 3.0)
18.11 16:15:38 [Server] INFO Using Superperms fallback ('group.[GROUPNAME]) for group support.
18.11 16:15:38 [Server] INFO Enabling MyWarp v3.0-SNAPSHOT+jenkins-b60.git-67b56dd
18.11 16:15:38 [Server] INFO Enabled
18.11 16:15:38 [Server] INFO Loaded 2 maps of world 'world_the_end'.
18.11 16:15:38 [Server] INFO Loaded 2 maps of world 'world_nether'.
18.11 16:15:38 [Server] INFO Full render for world 'world' restored
18.11 16:15:38 [Server] INFO Loaded 3 maps of world 'world'.
18.11 16:15:38 [Server] INFO version 2.3-SNAPSHOT-1132 is enabled - core version 2.3-SNAPSHOT-2070
18.11 16:15:38 [Server] INFO Web server started on address 169.249.170.31:8200
18.11 16:15:38 [Server] INFO Loaded 14 lightings.
18.11 16:15:38 [Server] INFO Loaded 82 perspectives.
18.11 16:15:37 [Server] INFO Loaded 23 shaders.
18.11 16:15:37 [Server] INFO Mod Support processing completed
18.11 16:15:37 [Server] INFO Web interface permissions only available for online users
18.11 16:15:37 [Server] INFO Using Bukkit Permissions (superperms) for access control
18.11 16:15:37 [Server] INFO Added 1 custom biome mappings
18.11 16:15:37 [Server] INFO Enabling dynmap v2.3-SNAPSHOT-1132
18.11 16:15:37 [Server] INFO Made my Muizers :)
18.11 16:15:37 [Server] INFO Plugin enabled!
18.11 16:15:37 [Server] INFO Registering events...
18.11 16:15:37 [Server] INFO Preparing version 0.17
18.11 16:15:37 [Server] INFO Enabling CreativeFlySpeed v0.17
18.11 16:15:37 [Server] INFO Preparing start region for level 2 (Seed: 5709353826701685570)
18.11 16:15:37 [Server] INFO Preparing spawn area: 86%
18.11 16:15:36 [Server] INFO Preparing start region for level 1 (Seed: 5709353826701685570)
18.11 16:15:35 [Server] INFO Preparing spawn area: 76%
18.11 16:15:34 [Server] INFO Preparing spawn area: 10%
18.11 16:15:34 [Multicraft] Skipped 27 lines due to rate limit (30/s)
18.11 16:15:33 [Server] INFO Mob Spawn Range: 4
18.11 16:15:33 [Server] INFO -------- World Settings For [world_the_end] --------
18.11 16:15:33 [Server] INFO Nerfing mobs spawned from spawners: false
18.11 16:15:33 [Server] INFO Zombie Aggressive Towards Villager: true
18.11 16:15:33 [Server] INFO Experience Merge Radius: 3.0
18.11 16:15:33 [Server] INFO View Distance: 10
18.11 16:15:33 [Server] INFO Arrow Despawn Rate: 1200
18.11 16:15:33 [Server] INFO Item Merge Radius: 2.5
18.11 16:15:33 [Server] INFO Item Despawn Rate: 6000
18.11 16:15:33 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
18.11 16:15:33 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
18.11 16:15:33 [Server] INFO Max TNT Explosions: 100
18.11 16:15:33 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
18.11 16:15:33 [Server] INFO Structure Info Saving: true
18.11 16:15:33 [Server] INFO Random Lighting Updates: false
18.11 16:15:33 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
18.11 16:15:33 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
18.11 16:15:33 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
18.11 16:15:33 [Server] INFO Cocoa Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Vine Growth Modifier: 100%
18.11 16:15:33 [Server] INFO NetherWart Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Wheat Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Sapling Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Pumpkin Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Mushroom Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Melon Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Cane Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Cactus Growth Modifier: 100%
18.11 16:15:33 [Server] INFO Mob Spawn Range: 4
18.11 16:15:33 [Server] INFO -------- World Settings For [world_nether] --------
18.11 16:15:33 [Multicraft] Skipped 36 lines due to rate limit (30/s)
18.11 16:15:33 [Server] INFO Loading CreativeControl v0.8
18.11 16:15:33 [Server] INFO Loading WorldEdit v6.1.2;b3fbe8b
18.11 16:15:33 [Server] INFO Loading CreeperControl v0.5.1
18.11 16:15:33 [Server] INFO Loading MyWarp v3.0-SNAPSHOT+jenkins-b60.git-67b56dd
18.11 16:15:33 [Server] INFO Mod Support API available
18.11 16:15:33 [Server] INFO inhabitedTicks field not found - inhabited shader not functional
18.11 16:15:33 [Server] INFO Unload queue not found - default to unload all chunks
18.11 16:15:33 [Server] INFO version=git-Spigot-d60de0a-a951a88 (MC: 1.11)
18.11 16:15:33 [Server] INFO Loading dynmap v2.3-SNAPSHOT-1132
18.11 16:15:33 [Server] INFO Loading CreativeFlySpeed v0.17
18.11 16:15:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
18.11 16:15:33 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:15:33 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:15:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot1.11.jar:git-Spigot-d60de0a-a951a88]
18.11 16:15:33 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Essentials
18.11 16:15:33 [Server] ERROR Could not load 'plugins/Dynmap-Essentials-0.91.jar' in folder 'plugins'
18.11 16:15:33 [Server] INFO Set PluginClassLoader as parallel capable
18.11 16:15:33 [Server] WARN Plugin `Stop_Creative_Drop v1.2' uses the space-character (0x20) in its name `Stop Creative Drop' - this is discouraged
18.11 16:15:33 [Server] INFO Using epoll channel type
18.11 16:15:33 [Server] INFO Starting Minecraft server on 169.249.170.31:25582
18.11 16:15:32 [Server] INFO Generating keypair
18.11 16:15:32 [Server] INFO Debug logging is disabled
18.11 16:15:32 [Server] INFO Using 4 threads for Netty based IO
18.11 16:15:32 [Server] INFO Server Ping Player Sample Count: 12
18.11 16:15:32 [Server] INFO This server is running CraftBukkit version git-Spigot-d60de0a-a951a88 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
18.11 16:15:32 [Server] INFO Default game type: SURVIVAL
18.11 16:15:32 [Server] INFO Loading properties
18.11 16:15:32 [Server] WARN To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
18.11 16:15:32 [Server] INFO Starting minecraft server version 1.11

**Comment by TheE** [comment]
You are using an old version where a failure of the Locale check is not properly handled. If you want, give the [newest devBuild](https://thee140.ci.cloudbees.com/job/mywarp3_bukkit) a try. It will not solve the issue, but it should no longer crash MyWarp.

**Comment by TickleMeCthulhu** [comment]
I'll give it a shot! No matter how this works out, I really appreciate your help!

**Comment by TickleMeCthulhu** [comment]
Installed the devBuild- seems to work just fine!

**Comment by TheE** [comment]
I just pushed a change that should fix the issue completely. :)

**Comment by TickleMeCthulhu** [comment]
That's awesome! Thanks so much!
