### ISSUE TITLE
Private warps not being treated as such.

### ISSUE THREAD

**Issue by 0x1x2** [TheE/MyWarp#127]
Hello! - just an issue with the latest MyWarp (on Bukkit). Anybody can warp to private warps, with no errors in console.

Server is on 1.10.2.

**Comment by TheE** [comment]
Are you using the latest [devBuild](https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/)?

**Comment by 0x1x2** [comment]
oh n0pe was using the latest Bukkit one, sorry

**Comment by TheE** [comment]
So does this error still occur with build 140?

**Comment by TheE** [comment]
I cannot reproduce it myself, so I assume it is fixed.

**Comment by 0x1x2** [comment]
Sorry for being late this went to the back of my head, but no it is not fixed in the latest devbuild. Is it because I used /warp pcreate instead of /warp create then /warp private?

**Comment by TheE** [comment]
Followup from #128:

> I updated to the latest devbuild and the issue is still present.
>
>I'm creating private warps with /warp pcreate instead of /warp create + /warp private - is that the issue?
>
>Server is on 1.10.2.
>
> Plugins list: ScoreboardHotfix, SimpleBroadcast, Languages, MythicLib, PlugMan, CustomPolls, Spartan, DeluxeTags, DupePatch, TabListEdit, VKAutoPickup, ChatControl, FastAsyncWorldEdit, Vouchers, PermissionsEx, FeatherBoard, mcMMO, Lores, PlaceholderAPI, VoidWorld, VKBackPack, NametagEdit, Lockette, MyItems, OldCombatMechanics, TitleAPI, MultiSkyWars, VoxelSniper, LightAPI, WorldEdit, OpenInv, PacketListenerApi, BuycraftX, Votifier, VPNGuard, FastAsyncRedstone, MysteryBoxes, SQLibrary, CustomVillageTrades, Vault, PlayerPoints, ChestCommands, StaffPlus, MyWarp, MessageAnnouncer, Citizens, OnTime, ProtocolSupport, ObsidianAuctions, PerWorldInventory, WorldGuard, AuctionHouse, ASkyBlock, Essentials, SafeTrade, KitAdder, CS-CoreLib, EnjinMinecraftPlugin, RPGItems, NoFlyZone, ViaVersion, CommandNPC, QuickSell, BlockVersion, CompatNoCheatPlus, SilkSpawners, Multiverse-Core, ProtocolLib, Shopkeepers, ServerListPlus, MiniaturePets, ChestShop, EssentialsSpawn, HeadsPlugin, NoCheatPlus, LibsDisguises, eZProtector, HeavySpleef, Signs, CraftBook, Item2Chat, HolographicDisplays, PhatLoots, ServerSigns, ShopGUIPlus, pvparena, mcMMOAction, CrateReloaded, UltraCosmetics, HeadsInventory, ProtectionLib, PvPManager, MythicMobs, FurnitureLib, FurnitureMaker, MobStacker2, DiceFurniture, ProVotes, TokenEnchant, DeluxeChat, PrisonMines, EnchantmentBook, EBChance, Skript, SkStuff, skUtilities, skRayFall, SkQuery, Skellett, Umbaska, DailyBonus, LeaderHeads, ProQuests, ProQuests-Packages, BossShopPro, TrickyShops, ThirdCurrency

**Comment by TheE** [comment]
I closed #128 and reopened this ticket instead.

I tried the following steps to recreate the issue:
1. `/warp create test`
2. `/warp info test`: Warp name is **green**, the warp is public.
3. `/warp private test`
4. `/warp info test`: Warp name is **red**, the warp is private.

I am therefore still unable to recreate your issue. Could you please follow the four steps above and verify that the name in step 4 is green and not red?

**Comment by 0x1x2** [comment]
alright I'll do this as soon as I get home

**Comment by 0x1x2** [comment]
Alright, just tested.

Warp name IS red, but people can still teleport to it given that they know the warp name.

**Comment by TheE** [comment]
Strange. Could you please check if regular users have the `mywarp.override.use` permission (maybe via some strange inheritance) which would allow them to use private warps without being invited?

**Comment by 0x1x2** [comment]
Found the permission and fixed it o.o

Thanks for the help! ;P
