### ISSUE TITLE
Not require " " for warp names with spaces?

### ISSUE THREAD

**Issue by q220** [TheE/MyWarp#141]
Would it be possible to be able to warp to places without requiring " " marks for warp names with spaces? Like how it used to work in MyWarp 2 it would search for the closest match and teleport you there, and in case of multiple results it would just show what options you had.

ie. /warp Over The == takes you to the warp with "Over The Bridge"

**Comment by TheE** [comment]
Unfortunately no.

Requiring quotation marks is an explicit design decision. The implementation in MyWarp 2 was quit inflexible in terms of command arguments: The warp name always had to be the last argument which is something I no longer want to enforce (e.g. when thinking about a rename command)
