### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#38]
Server_Version: Spigot 1.8.3
MyWarp_Version: Project MyWarp 3 (for Bukkit 1.7.9+)
Bug: Not an localization edit file
More_Info:
- Why is there not an localization file. So that i can edit the message's?

**Comment by TheE** [comment]
As stated in the [corresponding article](https://github.com/TheE/MyWarp/wiki/Localizations), configurable localizations are not yet implemented in the current builds of MyWarp but are planned.

See #33 for more information.

**Comment by DutchUser** [comment]
Oke But then i got also an other little 'issue'
On my other server i got an little localization issue
Server_Verion: Spigot v1.7.10 RO.1 (#1649 build 20141113a - 1.8 Compatible!) *
MyWarp_Version: MyWarp v2.6.5
More_Info:
- When i edit the localization file then mywarp goes normaal english
- PS: Its Dutch

Edit_Version: http://pastebin.com/nUYmX4TW
Non_Edit_Version: http://pastebin.com/e5D3yG2J

And yes i use Notepad++
So where i edit it wrong?

**Comment by TheE** [comment]
* What is the name of the edited file?
* Could you post the `localization` section of your configuration?
* What is the locale of the Minecraft client used for testing?

**Comment by DutchUser** [comment]
1, mywarp_lang_en
2, localization:
       defaultLocale: en_US
       perPlayer: true
3, MC Client 1.8.1 

And what try you to say with 'Testing'?

**Comment by DutchUser** [comment]
I have also an other issue with MyWarp V2.6.5 
I somebody invite an player to his warp
an that player does /mw accept hes got an error that there are not warp invite's 
but that player can use the warp. So after all. The player invite him that other player accept it then that player get an error but hey can use that warp also with that error

**Comment by TheE** [comment]
I think you misunderstood how the system works. Please do the following:

* Rename the edited file to `mywarp_lang_nl.yml`.
* Edit your configuration and set `localization.defaultLocale` to `nl_NL`.
* Make sure that your client uses the Dutch localization (meaning Minecraft's localizations).

----

The `/warp accept` command has nothing to do with invitations. It accepts a warp that has been given to the user (`/warp give <name>`).

**Comment by DutchUser** [comment]
This problem is not fix. Because i do what you say
And hes stay use default engels.
MyWarps Config:
localization:
  defaultLocale: nl_NL
  perPlayer: true
File_Name:
mywarp_lang_nl.yml

**Comment by TheE** [comment]
Have you restarted your server after making the changes? Have you tried to set `localization.perPlayer` to `false`?

**Comment by DutchUser** [comment]
Yes. I restart more then 1 time ik think like 10 time's still hes not working. Also if I set that. localization.perPlayer to false instead of true. But he's stay doing english messages

**Comment by DutchUser** [comment]
This are the things that i try.
Rename the localization to 'mywarp_lang_nl.' (and yml)
Change config to 'nl_NL'
localization.perPlayer to 'false'
and restart the server more times

**Comment by DutchUser** [comment]
Can it ben that i edit things that not must be edit like codes that mywarp must have to work

**Comment by DutchUser** [comment]
Because i edit it now again but now i do only words not like '' or . and now hes working

**Comment by TheE** [comment]
Right, that's it. The version you posted above is not valid YAML (tested against [this](http://yaml-online-parser.appspot.com/) parser) - sorry I did not check that before.

**Comment by DutchUser** [comment]
Nvm. Its also my mistake because i don't etst it realy good. But now we now why hes going broken :)
Anyway do you now when people can edit message on MyWarp 3?

**Comment by TheE** [comment]
The feature will not be in the first beta witch will be release shortly but should be implemented soon afterwords. Again, subscribe to #33 to know when the feature is implemented.

Basically I just need to setup an external localization service ([crowdin](https://crowdin.com/) or similar) to crowd-source localizations, but I do not have the time to look into this at the moment.

**Comment by DutchUser** [comment]
Oke. Take your time :p V2.6.5 is fine. Also because helping the players with relocate not an BIG deal is xD. Anyway Thx's again for the fast reactions :)
