### ISSUE TITLE
insufficient permissions

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#39]
I updated from mywarp-bukkit-3.0-SNAPSHOT-all-#50 to mywarp-bukkit-3.0-SNAPSHOT-all-#59 to find out my players don't have sufficient permissions to use warps. So I downgraded back one version at a time till I found out that mywarp-bukkit-3.0-SNAPSHOT-all-#55 works fine. I am running PermissionsEx-1.23.1 and craftbukkit 1.8.3

**Comment by TheE** [comment]
Starting with devBuild#56 (commit 4ee8ea5a8a3130bd5f5959ade29e392692004d74), permissions have been changed and need to be adjusted, see [here](https://github.com/TheE/MyWarp/wiki/Update-from-2.6.x-to-3.x#permissions).

**Comment by Ironic8b498** [comment]
Sorry should of searched for my problem on your site, was late at night and wasn't thinking.
