### ISSUE TITLE
config limits not working

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#41]
Ok got the config to load without errors, had a little issue with typo's but I got it under control now. I changed enabled under Limits to true. Seems to use default limits. Just can't seem to get the limits to work per world. I have mywarp.limit.<groupname> set to each of the ranks. I still can't get the limits to work.
http://pastebin.com/G9kSbQ0u mywarp config
http://pastebin.com/0FKeDHvq perms

tp make your wiki easier to understand I think you should add how to add a rank that is a number, I have three groups 0, 1, 2 and not all server owners may know they need to add ' to allow the script to run. Also I'm just a little fuzzy on the mywarp.limit.disobey which means to over ride set limits default or group limits?

**Comment by TheE** [comment]
On ticket per issue please, I will reopen #40.
