### ISSUE TITLE
Economy functions don't work properly on latest dev build

### ISSUE THREAD

**Issue by Islid** [TheE/MyWarp#47]
Versions:

Spigot: 44c59bf-8f0f4ed API version 1.8.7-R0.1-SNAPSHOT
MyWarp: MyWarp v. 3.0, dev build #80
Vault: 1.5.3-b37
CraftConomy3: 3.2.2-SNAPSHOT-45dd885-trv175

MyWarp config: http://pastebin.com/FaMSqEKV

Issue: For some reason, despite assigning the permission mywarp.economy.standard to players and ensuring they lack the mywarp.economy.disobey permission (even going so far as to explicitly remove that one in GroupManager), creating, moving, renaming, or any other functions of warps do not charge them any money despite being assigned in the config to do so.

**Comment by Islid** [comment]
Oh, I almost forgot - if you need debug logs, startup logs, or anything else, just let me know - I didn't know how much to provide and what would be useful for you.

**Comment by TheE** [comment]
The information you provided where enough, thank you. Most users are not as precise...

The issue should be fixed in the latest dev build. Please let me know if it works or you encounter other issues.

**Comment by Islid** [comment]
Alright, I will test the latest build now. Thank you!
