### ISSUE TITLE
Irregular handling of AuthorizerExceptions for '/warp <warp>'

### ISSUE THREAD

**Issue by RustyDagger** [TheE/MyWarp#49]
Console error: http://pastebin.com/u5p7wf4w
My mywarps Config can be found here: http://pastebin.com/eU0AF5iQ

How to cause the issue. 
Have an admin or player to set a warp using /warp set Name
Get another player with the user permissions from below to try and /warp Name

My users Have the Permissions:

    - mywarp.cmd.private
    - mywarp.cmd.help
    - mywarp.cmd.public
    - mywarp.cmd.uninvite
    - mywarp.cmd.invite
    - mywarp.cmd.give
    - mywarp.cmd.info
    - mywarp.cmd.list
    - mywarp.cmd.assets.self
    - mywarp.cmd.welcome
    - mywarp.cmd.update
    - mywarp.cmd.delete
    - mywarp.cmd.create-private
    - mywarp.cmd.create-public

Having these permissions prevents the issue happening but its admin stuff and cant be given to players.

    - mywarp.cmd.to
    - mywarp.cmd.private.force
    - mywarp.cmd.public.force
    - mywarp.cmd.player
    - mywarp.cmd.assets

I have not tried build 81 as of yet But from looking at the changes listed It does not seem as tho this would of been fixed If you need any more info please just ask I should get an email alert and reply within 24 hours.

**Comment by TheE** [comment]
The error, as far as MyWarp is concerned, should be fixed in the latests devBuild.

Your users still need to have the `mywarp.cmd.to` to actually use warps via the `/warp <warp>` and `/to <warp>` commands (both are aliases).

**Comment by RustyDagger** [comment]
Thank You for the quick turn around on this Issue. Hmm Not sure how I managed to Screw up the perms.. Oh well Bit of A Bit of B :+1:
