### ISSUE TITLE
Allow a public but hidden warp for use in quests

### ISSUE THREAD

**Issue by rinchen** [TheE/MyWarp#5]
Hi,

Feature request. Please allow public warps to be hidden in the /warp list view for the purposes of player driven quests/adventures.  For example, after adventuring through a special server area a player comes across a sign that says "To get to the Secret Citadel issue /warp secretcidatel".  If a player listed public warps they wouldn't see that so the only way to discover the warp is to either a) be told by someone or b) discover the hint sign.

Thanks,

R

**Comment by TheE** [comment]
After some consideration public but hidden warps is not something I am going to add. May main concern is that a 'hidden' clashes with the automatic matching of warp names, including the popularity algorithm.

The right way to solve the situation described above is to have a private warp created by an admin where a certain permission-group is invited. When a player reaches the point to access the warp, he is added to the permission group by a third-party plugin.

If automatic teleports are needed I would suggest to uses an other plugin, such as WorldGuard's teleport region which might solve the problem better than a warp based approach ever could.
