### ISSUE TITLE
The Give command

### ISSUE THREAD

**Issue by TrapMaster123** [TheE/MyWarp#70]
my issue is simple i can use the give warp command however lack of a command to accept it?

**Comment by TheE** [comment]
I am not sure if I understand you correctly: Warps are not accepted via command, but instead using a more complex mechanisms that allows the receiving player to send plain-text answers like "yes", "no" or "info".

If you want to give the warp to a player directly, without asking him to accept it first, you can use the `-d` flag like so: `/warp give -d <player> <warp>`. This will still fail if the receiving player would violate any warp-limits by receiving the warp. If you want to ignore limits too, you can use the `-f` flag like so: `/warp give -d -f <player> <warp>`
