### ISSUE TITLE
Mywarp don't seem to work

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#75]
I'm running a bungee server and mywarp 3.0 build 99 is on a spigot server 1.8.8. If I type /warp with or without a warp name I get in chat "/warp <pagenumber:warp> [player]" works fine on my old server which was not using bungeecord. Trying to switch over to bungeecord. If I run a fresh install of mywarp it works fine, just when I copy the mywarp folder from one server to the other I have issues.

**Comment by TheE** [comment]
This output is definitely not send by MyWarp, so I assume that some other plugin already uses the `warp` command. Can you try to use `/mw <warp>` or `/mywarp <warp>` instead?

**Comment by Ironic8b498** [comment]
it must of been essentials, I have figured it out since I left this message, putting it in text I seen something I missed, I left configuration and just moved database now I just need to fix config to limit amount of warps for each group.

**Comment by TheE** [comment]
Ok, glad it is working now. :)
