### ISSUE TITLE
Strange limit thing, (Again)

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#76]
Hello. I found an strange issue, If you remove worlds form the server will /warp limits not work anymore. I cleaned my worlds today because there was some that i not using anymore. And after that /warp limits is not working anymore. And if i try todo /warp limits i get "The oparation tries to access the world <Kinda UUID text> That is currently not present on the server" How can i fix this? Also why mywarp not just remove the world from the DB or something. I have it now 2 times and first i just remove the DB's but now it becoming anoying and because if have some players with warps.

MyWarp DB's: (Do you know a way that I can put the DBs somewhere then you can download them?)
Mywarp version: MyWarp v3.0-beta-3 
Server Version: 1.8.8

**Comment by TheE** [comment]
Unfortunately there is no way for me to know when a world is deleted on the server. I can only track when a world is _unloaded_ witch can happen regularly, e.g. to regenerate the terrain or to do external maintenance work upon the world. In such cases you normally do not want the warps within this world to be deleted.

With the addition of #60 this could perhaps be improved, I could also add some warning messages in the console when a world is unloaded.

To solve you specific case, please send the database file to `thee[at]online[dot]de` or upload it on [Zippyshare](http://www.zippyshare.com/). Do you now the name of a warp that defiantly is _within_ the deleted world? I could than remove all warps within this world manually and send the deited database back to you.

**Comment by DutchUser** [comment]
I uploaded all my MyWarp files to make sure you have what you need.

config.yml, http://www116.zippyshare.com/v/x6y88ODk/file.html
profiles.db, http://www116.zippyshare.com/v/6Y7ONEo4/file.html
warps.h2.db, http://www116.zippyshare.com/v/J5LrD76O/file.html
warps.lock.db. http://www116.zippyshare.com/v/REUg0AqM/file.html

**Comment by TheE** [comment]
Do you know the **name** of a warp on the **world that was deleted**?

**Comment by DutchUser** [comment]
I deleted multiple worlds so no i don't know anymore Which worlds are deleted. If you want the world that not must deleted from the db's its are the next worlds, 
normal,Shop,Survival,Survival_nether Survival_the_end,FreeSpawn,PMCNetherContest

**Comment by DutchUser** [comment]
After removing some warps because this takes to long the command /warp limits working again so close this issue ticket.

**Comment by DutchUser** [comment]
Ow forgot something. I have an strange thing with the limits.
I maked an limt for group "God" nu the takes the limits from King (1 rank lower)
also pex have the negative permission for the "King" limit group

    - -mywarp.limit.King
    - mywarp.limit.God

    God:
      totalLimit: 29
      publicLimit: 3
      privateLimit: 26

Still the plugin takes the King limit? How can i fix this?

**Comment by DutchUser** [comment]
bump:

MW limit name: a:
Permission mywarp.limit.a

MW limit name: b:
Permission mywarp.limit.b

MW limit name: c:
Permission: mywarp.limit.c

MW limit name: d:
Permsission: mywarp.limit.d

http://pastebin.com/ukLUK1rM

not one is working. Also it says "http://nl.tinypic.com/view.php?pic=23u90dj&s=9#.VvgZ7uKLS70" Those limits are not set at all. Where those come from?

**Comment by TheE** [comment]
The limit is defined in the config, it is the default limit! The default limit always applies when the user does not have any of the configured limits, that means he does not have the `mywarp.limit.a`, `mywarp.limit.b` etc. permission!

To be sure, I just double checked if there are any issues with limits: I cannot reproduce any problems.

**Comment by DutchUser** [comment]
I fixed it with the pex negatief permissions, But i have an other, Do you know when we are enable to change the message's?

**Comment by TheE** [comment]
Messages can be changed already, see [here](https://github.com/TheE/MyWarp/wiki/Localizations).

If you want to create a Dutch translation, please consider using the [official crowdin](https://crowdin.com/project/mywarp) to create it so I can bundle it with MyWarp.
