### ISSUE TITLE
Can't teleport player when type /warp shop

### ISSUE THREAD

**Issue by NickFirenzo** [TheE/MyWarp#78]
Hi,
I need help about teleport to warp. When default player type `/warp shop`, getting: You will be teleported to "shop" in 3 seconds. 3 seconds passed and nothing. Player isn't teleport to shop. When you are /op you can teleport succsess.

config.yml: http://pastebin.com/f6PbK2q3

Can you tell me how to fix? :(
I'm using this permissions for DEFAULT member

    - mywarp.cmd.to
    - mywarp.cmd.create-public
    - mywarp.cmd.delete
    - mywarp.cmd.update
    - mywarp.cmd.welcome
    - mywarp.cmd.list
    - mywarp.cmd.info

**Comment by TheE** [comment]
To be clear, the player did not move or receive any damage after he used `/warp shop`? Are there any error message visible in the console?

**Comment by NickFirenzo** [comment]
No messages, when type /warp shop say You will teleported to "shop" in 3 seconds. After 3 seconds has no effect, you are not teleported. When 
timers:
  enabled: false

When timer is FALSE players can succsess teleported without timers.

**Comment by TheE** [comment]
I assume I fixed the issue with c20cfa0. Could you give the latest devBuild a try?
