### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by James18plays** [TheE/MyWarp#88]
Need help with Permissions. Cant figure out how to allow users (not-opped) to use warp command. Help Please!

**Comment by TheExceed** [comment]
mywarp.cmd.to

**Comment by James18plays** [comment]
@TheExceed Where to i put that at? thats my problem

**Comment by TheExceed** [comment]
You default rank if you're using inheritance, if you are not then every rank needs it

**Comment by James18plays** [comment]
@TheExceed I new to the whole config can you explain a little more please

**Comment by James18plays** [comment]
@TheExceed Thank you for the help My brother and I figured it out using a different Plugging but if you could finish explaining it would be great because id love to use this plugging

**Comment by TheExceed** [comment]
@James18plays Which plugin are you using?

**Comment by James18plays** [comment]
@TheExceed Right now we are using SetSpawn pluggin only one we can figure out how to use

**Comment by TheExceed** [comment]
Do you not have a permissions plugin?

**Comment by James18plays** [comment]
Pex. and PermissionsBukkit

**Comment by TheExceed** [comment]
Chose one or the other. Prolly pex.
What youll wanna do is this:
/pex group default add mywarp.cmd.to

**Comment by James18plays** [comment]
Okay thank you ^_^ i will try that

**Comment by James18plays** [comment]
that you it worked. ^_^
