### ISSUE TITLE
Error when someone does a warp command

### ISSUE THREAD

**Issue by Hades909** [TheE/MyWarp#89]
So some of my players can warp and others can not. its random some times the player can do the command and some times they can not. I think this error might have some thing to do with it but i am not fully sure. 

[Error log]
http://pastebin.com/W1am1vCf

**Comment by TheE** [comment]
Are you using Multiverse inventories to separate inventories per world? And, if so, is it possible that usage of warps only fails if the player it in another world than the warp?

From the log you posted, it looks like some error within Multiverse inventories cancels the teleport. Are you using the most up to date version of Multiverse inventories?

**Comment by Hades909** [comment]
Yes we are using the latest dev builds

**Comment by TheE** [comment]
Once again: Is it possible that usage of warps only fails if the player it in another world than the warp?

**Comment by Hades909** [comment]
no it does not  work even in the same world.it says a internal error when doing the command. and its not everyone that gets affected by this.

**Comment by TheE** [comment]
Do you have any error of of a failing warp when the player is one the same world as the warp?

The issue posted in the first post is defiantly caused by Multiverse Inventories, therefore it is out of my control. However, I assume that Multiverse Inventories is only involved when warp and player are not within the same world, so this might be another issue.

**Comment by Hades909** [comment]
yes Multiverse inventories is really messed up and I think so i'm looking for a substitute for it. Ill get u a log of the error when i get the chance.

**Comment by Hades909** [comment]
here is a screen shot of what happens but in console no error
http://i.imgur.com/gz1GoDR.png

**Comment by TheE** [comment]
Ok, this happens if a world that contain warps is removed (see #93). I work on a fix but this will take some time.

Are you able to manually edit the database? Essentially you need to remove all warps on the world with the ID you see in your screenshot (if not I'll help you).

**Comment by Hades909** [comment]
https://www.dropbox.com/s/h2c1jwpex8kvz32/MyWarp.zip?dl=0

here is a link to my  mywarp data config and everything. i use flat file because i could never get the database working properly

**Comment by TheE** [comment]
I removed the world in question and all warps on it: https://dl.dropboxusercontent.com/u/13777859/modified_warps_db.zip Simply replace the database on the server with the database from the database from the zip 

Please let me know if it works, I'll than remove both download links.

**Comment by Hades909** [comment]
still have some errors on other pages. want me to send u the current worlds that are active?
