### ISSUE TITLE
Console SPAM error

### ISSUE THREAD

**Issue by NickFirenzo** [TheE/MyWarp#90]
Getting console spam error, how can I fix it?
error: http://pastebin.com/69DrNeun

**Comment by TheE** [comment]
there seems to be some sort of error with updating the name of the player who logged in. Could you please send me the full server log (there are several lines missing before and after the snippet posted above)?

**Comment by TheE** [comment]
I am closing this issue as I am unable to reproduce it without additional information.

However, feel free to comment (and reopen) if you still encounter the issue!
