### ISSUE TITLE
insufficient permission

### ISSUE THREAD

**Issue by voigtman** [TheE/MyWarp#92]
After updating to build 110
my players are unable to use /warp
permissions given:```

    - mywarp.cmd.to
    - mywarp.world-access.world
    - mywarp.world-access.world_nether
    - mywarp.sign.create.self
    - mywarp.sign.create
    - mywarp.sign.use
```

player is unable to use /warp
instead they're told they have "insufficient permission"

**Comment by voigtman** [comment]
It would seem only players with permissions to create warps have the ability to use them

**Comment by TheE** [comment]
Strange, I'll have to investigate.

Until then you should probably downgrade to the build you used before (103?). To fix the localization problems, disable the per player localization by setting localization.per-player to false into the configuration file.



--
Paul Hasselkuss
Wahnenkamp 22
42697 Solingen

Privat: 0212 6588018
Mobil: 0176 63823627
Mail: paul@hasselkuss.com

**Comment by voigtman** [comment]
Thank you very much for the help!

**Comment by TheE** [comment]
Could you test the latest devBuild (#111)?

I think the issue was caused by a bug within the command framework MyWarp uses which I just fixed.

**Comment by voigtman** [comment]
Thank you very much. I will give it a test. Keep up the great work you do, please :)

**Comment by voigtman** [comment]
seems to have fixed the issue. Thank you very much!

On Sun, Apr 3, 2016 at 3:31 PM, - Voigtman <voigtmanmc@gmail.com> wrote:

> Thank you very much. I will give it a test. Keep up the great work you do,
> please :)
>
> Sent from my iPhone
>
> On Apr 3, 2016, at 6:24 AM, TheE <notifications@github.com> wrote:
>
> Could you test the latest devBuild (#111)?
>
> I think the issue was caused by a bug within the command framework MyWarp
> uses which I just fixed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TheE/MyWarp/issues/92#issuecomment-204947173>
>
>


-- 

Jason
========
https://voigtlandMC.net
IP: play.voigtlandmc.net
Twitter: @VoigtlandMC
IGN: Voigtman
