### ISSUE TITLE
SquirrelID Lag

### ISSUE THREAD

**Issue by troyboy50** [TheE/MyWarp#98]
Our server seems to be hanging due to MyWarp. Seems to happen when players join and occasionally when a player warps. Using H2 storage. Here are a couple timings reports I used to identify the issue:
https://timings.spigotmc.org/?url=15839688
https://timings.spigotmc.org/?url=15839665

Am I doing something wrong or is this indeed an issue on MyWarp's end?

**Comment by TheE** [comment]
There have been a few reports about similar behavior, but this appears to be the most clear one.

Technically MyWarp updates its name cache whenever a player logs in, which blocks the server's main thread for a short period of time. Normally this should not harm performance, but I assume on busy servers it might be a problem.

I will investigate if I can move the cache update to another thread by using `AsyncPlayerPreLoginEvent` (or of course Bukkit receives a functional cache API but that is not going to happen).
